config/routes.rb
Rails.application.routes.draw do
  # resources :category_records
  # resources :records
  # resources :categories

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end
    unauthenticated do
      root 'splash#index', as: :unauthenticated_root
    end
    get '/users/sign_out' => 'devise/sessions#destroy'
  resources :users, only: [:index]
  end
  resources :categories do 
    # resources :records, except: [:index]
    resources :records
  end
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :category_records, dependent: :delete_all
  has_many :categories, through: :category_records

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  # validates :amount, presence: true, numericality: { greater_than: 0, less_than: 10000 }
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: %i[show edit update destroy]
  before_action :authenticate_user!
  load_and_authorize_resource :category

  def index
    @records = Record.all
  end

  def show
    # @category = Category.find(params[:id])
    # @records = @category.records.order(created_at: :desc)
    @category = Category.find(params[:category_id])
    @record = @category.records.find(params[:id])
  end

  # GET /records/new
  def new
    @record = Record.new
    @category = Category.find(params[:category_id])
  end

  # GET /records/1/edit
  def edit; end

  def create
    @category = Category.find(params[:category_id])
    @record = Record.new(record_params)
    @record.user_id = current_user.id
    @record.save!
    category_record = @category.category_records.new(record: @record)
    # OR category_record = CategoryRecord.create!(category: @category, record: @record)

    respond_to do |format|
      if category_record.save
        format.html { redirect_to category_url(@category), notice: 'Transaction was successfully created.' }

      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1 or /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to category_record_url(@category, @record), notice: 'Record was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1 or /records/1.json
  def destroy
    @record = set_record
    # @record.delete
    @record.destroy

    respond_to do |format|
      format.html { redirect_to category_url(@category), notice: 'Record was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_record
    @record = Record.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def record_params
    params.require(:record).permit(:name, :amount)
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_with(model: [category, record], id: "new-tran-from")  do |form| %>
  <% if record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, required: true, placeholder: "Name"  %>
  </div>

  <div  class="input">
    <%= form.label :amount, style: "display: block" %>
    <% form.text_field :amount %>
    <%= form.number_field :amount, placeholder: "Amount", required: true  %>

  </div>

  <div>
    <% form.label :user_id, style: "display: block" %>
    <% form.text_field :user_id %>
  </div>
<% end %>

app/views/records/_record.html.erb
<div class='record show d-flex flex-center' id="<%= dom_id record %>">
  <p>
    <strong><%= record.name %></strong>
  </p>
  <p>
    <strong><span><%= record.amount %><span> $</strong>
  </p>
</div>

app/views/records/edit.html.erb
<nav class="header-categories d-flex flex-center">
  <div class="icons">
    <%= link_to  category_record_path(@category, @record) do %>
      <i class="fa-solid fa-arrow-left back"></i>
    <% end %>
  </div>
  <h1 class="transaction-header-nav">Editing Transaction</h1>
  <div class="actions-save">
    <input type="submit" name="commit" value="save" class="login-button new-edit-cat" form="new-tran-from" data-disable-with="Log in">
  </div>
</nav>

<%= render "form", category: @category, record: @record %>

app/views/records/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Records</h1>

<div id="records">
  <% @records.each do |record| %>
    <%= render record %>
    <p>
      # <%= link_to "Show this record", category_records_url %>
    </p>
  <% end %>
</div>

<%= link_to "New record", new_category_record_path %>

app/views/records/new.html.erb
<nav class="header-categories d-flex flex-center">
  <div class="icons">
    <%= link_to  category_path(@category) do %>
      <i class="fa-solid fa-arrow-left back"></i>
    <% end %>
  </div>
  <h1 class="transaction-header-nav">NEW TRANSACTION</h1>
  <div class="actions-save">
    <input type="submit" name="commit" value="save" class="login-button new-edit-cat" form="new-tran-from" data-disable-with="Log in">
  </div>
</nav>

<%= render "form", record: @record, category: @category %>

<br>

<div class="">
  <% link_to "Back to records", category_records_path(@category, @record) %>
  <% link_to "Back to category", category_path(@category) %>
</div>

app/views/records/show.html.erb
<p style="color: green"><%= notice %></p>

<nav class="header-categories d-flex flex-center">
  <div class="icons">
    <%= link_to  category_path(@category) do %>
      <i class="fa-solid fa-arrow-left back"></i>
    <% end %>
  </div>
  <h1>Transaction details</h1>
</nav>

<div class="transactions show d-flex"> 
  <h2></h2>
  <ul class="categoies-records">
    <li id="category-record" class="show">
      <%= render @record %>

      <ul>
        <li class='record d-flex flex-center'>
          <p> <strong>Create Date: </strong> <p>
          <span class="date d-flex"> <%= @record.created_at.strftime('%Y') %>
            <span>_<%= @record.created_at.to_formatted_s(:short) %></span>
          </span>
        </li>

        <li class='record d-flex flex-center'>
          <% if @record.created_at == @record.updated_at %>
            <p><strong>No Update yet !!!</strong></p>
          <% else %>
            <p> <strong>Update Date: </strong> <p>
            <span class="date d-flex"> <%= @record.updated_at.strftime('%Y') %>
              <span>_<%= @record.updated_at.to_formatted_s(:short) %></span>
            </span>
          <% end %>
        </li>
      </ul>
    </li>
  </ul>

  <div class="btns-record d-flex flex-center">
      <div class="actions-btn">
        <%= link_to "Update", edit_category_record_path(@category, @record) %>
      </div>
      <div class="delete-btn">
        <%=button_to 'Delete', {:controller => :records, :action => 'destroy', :id => @record.id}, :method => :delete%>
      </div>
  </div>

</div>